
```{r}
                ############################
                ###       BOSTON        ####
                ############################
library(tidyverse)
library(dplyr)
airbnb_Boston <- read.csv("~/Desktop/Boston_joined_block.csv", sep = ",", header = TRUE, stringsAsFactors=FALSE)
# Correcting Tract ID
table(nchar(airbnb_Boston$CT_ID_10)) 
airbnb_Boston$New_CT <- NA
for (i in 1:nrow(airbnb_Boston)) {
  if (nchar(airbnb_Boston$CT_ID_10[i]) == 3) {
     airbnb_Boston$New_CT[i] <- paste0("25025000", airbnb_Boston$CT_ID_10[i])
  } else if (nchar(airbnb_Boston$CT_ID_10[i]) == 5) {
    airbnb_Boston$New_CT[i] <- paste0("250250", airbnb_Boston$CT_ID_10[i])
  } else 
   airbnb_Boston$New_CT[i] <- paste0("25025", airbnb_Boston$CT_ID_10[i])
}

# Checking
table(nchar(airbnb_Boston$New_CT))
table(startsWith(airbnb_Boston$New_CT, '25'))
airbnb_Boston <- airbnb_Boston [,-109]
airbnb_Boston <- rename(airbnb_Boston, CT_ID_10 = New_CT)
airbnb_Boston <- rename(airbnb_Boston, TOWN = REALTOWN)
airbnb_Boston <- rename(airbnb_Boston, COUNTY = COUNTYFP10)
######################################
###   Cross Sectional Metrics       ##
######################################
######### ListingsFreq_Cross ############
library(reshape2)
ListingsFreq_Cross <- melt(table(airbnb_Boston$CT_ID_10),id.vars=c("airbnb_Boston$CT_ID_10"))
names(ListingsFreq_Cross)[1] <- 'CT_ID_10'
names(ListingsFreq_Cross)[2] <- 'ListingsFreq_Cross'

#############  MedianRent_Cross ################
# Convert price to numeric
airbnb_Boston$price <- as.numeric(gsub('[$,]', '', airbnb_Boston$price))
MedianRent_Cross <- aggregate(price ~ CT_ID_10, data=airbnb_Boston, median)
names(MedianRent_Cross)[2] <- 'MedianRent_Cross'
# Merge both MedianRent_Cross and ListingsFreq_Cross 
cross <- merge(ListingsFreq_Cross, MedianRent_Cross, by = "CT_ID_10")

#####################################
###      Longitudinal Metrics      ##
#####################################

# Fiding number of listings for each month for Airbnb dataset
table(airbnb_Boston$Month)

######### ListingsFreq_January ########
January <- airbnb_Boston[airbnb_Boston$Month == "January",]
ListingsFreq_Jan <- melt(table(January$CT_ID_10),id.vars=c("January$CT_ID_10"))
names(ListingsFreq_Jan)[1] <- "CT_ID_10"
names(ListingsFreq_Jan)[2] <- "ListingsFreq_Jan"

######### ListingsFreq_February ########
February <- airbnb_Boston[airbnb_Boston$Month == "February",]
ListingsFreq_Feb <- melt(table(February$CT_ID_10),id.vars=c("February$CT_ID_10"))
names(ListingsFreq_Feb)[1] <- "CT_ID_10"
names(ListingsFreq_Feb)[2] <- "ListingsFreq_Feb"

######### ListingsFreq_March ########
March <- airbnb_Boston[airbnb_Boston$Month == "March",]
ListingsFreq_Mar <- melt(table(March$CT_ID_10),id.vars=c("March$CT_ID_10"))
names(ListingsFreq_Mar)[1] <- "CT_ID_10"
names(ListingsFreq_Mar)[2] <- "ListingsFreq_Mar"

#######	ListingsFreq_April #########
April <- airbnb_Boston[airbnb_Boston$Month == "April",]
ListingsFreq_Apr <- melt(table(April$CT_ID_10),id.vars=c("April$CT_ID_10"))
names(ListingsFreq_Apr)[1] <- "CT_ID_10"
names(ListingsFreq_Apr)[2] <- "ListingsFreq_Apr"

######	ListingsFreq_May ##########
May <- airbnb_Boston[airbnb_Boston$Month == "May",]
ListingsFreq_May <- melt(table(May$CT_ID_10),id.vars=c("May$CT_ID_10"))
names(ListingsFreq_May)[1] <- "CT_ID_10"
names(ListingsFreq_May)[2] <- "ListingsFreq_May"

###### ListingsFreq_June ##########
June <- airbnb_Boston[airbnb_Boston$Month == "June",]
ListingsFreq_Jun <- melt(table(June$CT_ID_10),id.vars=c("June$CT_ID_10"))
names(ListingsFreq_Jun)[1] <- "CT_ID_10"
names(ListingsFreq_Jun)[2] <- "ListingsFreq_Jun"

# Merging all months for listing frequency
January_February <- merge(ListingsFreq_Jan, ListingsFreq_Feb, by = "CT_ID_10", all = TRUE)
March_April <- merge(ListingsFreq_Mar, ListingsFreq_Apr, by = "CT_ID_10", all = TRUE)
May_June <- merge(ListingsFreq_May, ListingsFreq_Jun, by = "CT_ID_10", all = TRUE)
January_February_March_April <- merge(January_February, March_April, by = "CT_ID_10", all = TRUE)
all_months <- merge(January_February_March_April, May_June, by = "CT_ID_10", all = TRUE)

###### MedianRent_January #######
MedianRent_Jan <- aggregate(price ~ CT_ID_10, data=January, median)
names(MedianRent_Jan)[1] <- 'CT_ID_10'
names(MedianRent_Jan)[2] <- 'MedianRent_Jan'

###### MedianRent_February #######
MedianRent_Feb <- aggregate(price ~ CT_ID_10, data=February, median)
names(MedianRent_Feb)[1] <- 'CT_ID_10'
names(MedianRent_Feb)[2] <- 'MedianRent_Feb'

###### MedianRent_March #####
MedianRent_Mar <- aggregate(price ~ CT_ID_10, data=March, median)
names(MedianRent_Mar)[1] <- 'CT_ID_10'
names(MedianRent_Mar)[2] <- 'MedianRent_Mar'

###### MedianRent_April #####
MedianRent_Apr <- aggregate(price ~ CT_ID_10, data=April, median)
names(MedianRent_Apr)[1] <- 'CT_ID_10'
names(MedianRent_Apr)[2] <- 'MedianRent_Apr'

###### MedianRent_May ######
MedianRent_May <- aggregate(price ~ CT_ID_10, data=May, median)
names(MedianRent_May)[1] <- 'CT_ID_10'
names(MedianRent_May)[2] <- 'MedianRent_May'

###### MedianRent_June #####
MedianRent_Jun <- aggregate(price ~ CT_ID_10, data=June, median)
names(MedianRent_Jun)[1] <- 'CT_ID_10'
names(MedianRent_Jun)[2] <- 'MedianRent_Jun'

# Merging all months for median rent
January_February <- merge(MedianRent_Jan, MedianRent_Feb, by = "CT_ID_10", all = TRUE)
March_April <- merge(MedianRent_Mar, MedianRent_Apr, by = "CT_ID_10", all = TRUE)
May_June <- merge(MedianRent_May, MedianRent_Jun, by = "CT_ID_10", all = TRUE)
January_February_March_April <- merge(January_February, March_April, by = "CT_ID_10", all = TRUE)
all_months_rent <- merge(January_February_March_April, May_June, by = "CT_ID_10", all = TRUE)

# Merging all data together
all <- merge(cross, all_months, by = 'CT_ID_10', all = TRUE)
names(all)[1] <- 'CT_ID_10'
all <- merge(all, all_months_rent, by = 'CT_ID_10', all = TRUE)

# Add town and county to all
airbnb_Boston$CT_ID_10 <- as.numeric(airbnb_Boston$CT_ID_10)
all$TOWN <- airbnb_Boston$TOWN[match(all$CT_ID_10, airbnb_Boston$CT_ID_10)]
all$COUNTY <- airbnb_Boston$COUNTY[match(all$CT_ID_10, airbnb_Boston$CT_ID_10)]
# Correct County names
table(all$COUNTY)
all$COUNTY <-  ifelse(all$COUNTY == 17, "Middlesex County",
                      ifelse(all$COUNTY == 21, "Norfolk County","Suffolk County"))

# Replace NA values with 0 for numeric features
colnames(all)[apply(is.na(all), 2, any)] 
all$ListingsFreq_Jan[is.na(all$ListingsFreq_Jan)] <- 0
all$ListingsFreq_Feb[is.na(all$ListingsFreq_Feb)] <- 0
all$ListingsFreq_Mar[is.na(all$ListingsFreq_Mar)] <- 0
all$ListingsFreq_Apr[is.na(all$ListingsFreq_Apr)] <- 0
all$ListingsFreq_May[is.na(all$ListingsFreq_May)] <- 0
all$ListingsFreq_Jun[is.na(all$ListingsFreq_Jun)] <- 0
all$MedianRent_Jan[is.na(all$MedianRent_Jan)] <- 0
all$MedianRent_Feb[is.na(all$MedianRent_Feb)] <- 0
all$MedianRent_Mar[is.na(all$MedianRent_Mar)] <- 0
all$MedianRent_Apr[is.na(all$MedianRent_Apr)] <- 0
all$MedianRent_May[is.na(all$MedianRent_May)] <- 0
all$MedianRent_Jun[is.na(all$MedianRent_Jun)] <- 0
# Checking for NA values
colnames(all)[apply(is.na(all), 2, any)]
# Convert price to $
all$MedianRent_Cross <- paste0("$",all$MedianRent_Cross)
all$MedianRent_Jan <- paste0("$",all$MedianRent_Jan)
all$MedianRent_Feb <- paste0("$",all$MedianRent_Feb)
all$MedianRent_Mar <- paste0("$",all$MedianRent_Mar)
all$MedianRent_Apr <- paste0("$",all$MedianRent_Apr)
all$MedianRent_May <- paste0("$",all$MedianRent_May)
all$MedianRent_Jun <- paste0("$",all$MedianRent_Jun)

all <- all %>% select(CT_ID_10, ListingsFreq_Cross, MedianRent_Cross, ListingsFreq_Jan, ListingsFreq_Feb, ListingsFreq_Mar, ListingsFreq_Apr, ListingsFreq_May, ListingsFreq_Jun, MedianRent_Jan, MedianRent_Feb, MedianRent_Mar, MedianRent_Apr, MedianRent_May, MedianRent_Jun, TOWN, COUNTY) 

# Save as csv
write.csv(all,"~/Desktop/AIRBNB.Neighborhoods.Boston.csv ", row.names = FALSE)
```



```{r}
###################### BOSTON ##############################
airbnb <- airbnb_Boston
########## Binary Variables ##############
# host_is_superhost
airbnb[airbnb$host_is_superhost != "",]$host_is_superhost <- ifelse(airbnb[airbnb$host_is_superhost != "",]$host_is_superhost == "t", 1, 0)
# host_has_profile_pic
airbnb[airbnb$host_has_profile_pic != "",]$host_has_profile_pic <- ifelse(airbnb[airbnb$host_has_profile_pic != "",]$host_has_profile_pic == "t", 1, 0)
# host_identity_verified
airbnb[airbnb$host_identity_verified != "",]$host_identity_verified <- ifelse(airbnb[airbnb$host_identity_verified != "",]$host_identity_verified == "t", 1, 0)
# is_location_exact
airbnb$is_location_exact <- ifelse(airbnb$is_location_exact == "t", 1, 0)
# has_availability
airbnb$has_availability <- ifelse(airbnb$has_availability == "t", 1, 0)
# requires_license
airbnb$requires_license <- ifelse(airbnb$requires_license == "t", 1, 0)
# instant_bookable
airbnb$instant_bookable <- ifelse(airbnb$instant_bookable == "t", 1, 0)
# is_business_travel_ready
airbnb$is_business_travel_ready <- ifelse(airbnb$is_business_travel_ready == "t", 1, 0)
# require_guest_profile_picture
airbnb$require_guest_profile_picture <- ifelse(airbnb$require_guest_profile_picture == "t", 1, 0)
# require_guest_phone_verification
airbnb$require_guest_phone_verification <- ifelse(airbnb$require_guest_phone_verification == "t", 1, 0)

#############  property_type ##########
airbnb$property_type <- ifelse(airbnb$property_type == "Aparthotel", "AH", ifelse(airbnb$property_type == "Apartment", "APT", ifelse(airbnb$property_type == "Barn", "BA", ifelse(airbnb$property_type == "Bed and breakfast", "BB", ifelse(airbnb$property_type == "Boat", "BO", ifelse(airbnb$property_type == "Boutique hotel", "BH", ifelse(airbnb$property_type == "Bungalow", "BU", ifelse(airbnb$property_type == "Castle", "CSL", ifelse(airbnb$property_type == "Condominium", "CND", ifelse(airbnb$property_type == "Cottage", "COT", ifelse(airbnb$property_type == "Guest suite", "GS", ifelse(airbnb$property_type == "Guesthouse", "GH", ifelse(airbnb$property_type == "Hostel", "HSL", ifelse(airbnb$property_type == "Hotel", "HTL", ifelse(airbnb$property_type == "House", "HSE", ifelse(airbnb$property_type == "Houseboat", "HB", ifelse(airbnb$property_type == "In-law", "IL", ifelse(airbnb$property_type == "Loft", "LO", ifelse(airbnb$property_type == "Other", "O", ifelse(airbnb$property_type == "Serviced apartment", "SA", ifelse(airbnb$property_type == "Townhouse", "TH", ifelse(airbnb$property_type == "Villa", "V", 0))))))))))))))))))))))
# property_type is the type of properties for Airbnb listings. Types include: AH for Aparthotel, APT for Apartment, BA for Barn, BB for Bed and breakfast, BO for Boat, BH for Boutique hotel, BU for Bungalow, CSL for Castle, CND for Condominium, COT for Cottage, GS for Guest suite, GH for Guesthouse, HSL for Hostel, HTL for Hotel, HSE for House, HB for Houseboat, IL for In-law, LO for Loft, O for Other, SA for Serviced apartment, TH for Townhouse, and V for Villa.

############ room_type ###########
airbnb$room_type <- ifelse(airbnb$room_type == "Entire home/apt", "HA", ifelse(airbnb$room_type == "Hotel room", "HR", ifelse(airbnb$room_type == "Private room", "PR", ifelse(airbnb$room_type == "Shared room", "SR", 0))))
# room_type is the type of Airbnb listings, which include: HA for Entire home/apt, HR for Hotel room, PR for Private room, and SR for Shared room.

############ bed_type ###########
airbnb[airbnb$bed_type != "",]$bed_type <- ifelse(airbnb[airbnb$bed_type != "",]$bed_type == "Airbed", "AB", ifelse(airbnb[airbnb$bed_type != "",]$bed_type == "Couch", "CO", ifelse(airbnb[airbnb$bed_type != "",]$bed_type == "Futon", "FU", ifelse(airbnb[airbnb$bed_type != "",]$bed_type == "Pull-out Sofa", "POS", ifelse(airbnb[airbnb$bed_type != "",]$bed_type == "Real Bed", "RB", 0)))))
# bed_type is the type of beds in Airbnb listings. Types of bed include: AB for Airbed, CO for Couch, FU for Futon, POS for Pull-out Sofa, and RB for Real Bed.

########## cancellation_policy #########
airbnb$cancellation_policy <- ifelse(airbnb$cancellation_policy == "flexible", "FLEX", ifelse(airbnb$cancellation_policy == "moderate", "MOD", ifelse(airbnb$cancellation_policy == "strict", "STR", ifelse(airbnb$cancellation_policy == "strict_14_with_grace_period", "STR_14", ifelse(airbnb$cancellation_policy == "super_strict_30", "STR_30", ifelse(airbnb$cancellation_policy == "super_strict_60", "STR_60", 0))))))
# cancellation_policy include: FLEX for flexible, MOD for moderate, STR for strict, STR_14 for strict_14_with_grace_period, STR_30 for super_strict_30, and STR_60 for super_strict_60.

airbnb <- airbnb %>% select(name, summary, space, description, neighborhood_overview, notes, transit, access, interaction, house_rules, id, Year, Month, listing_url, thumbnail_url, medium_url, picture_url, xl_picture_url, property_type, room_type, accommodates, bathrooms, bedrooms, beds, bed_type, amenities, square_feet, price, weekly_price, monthly_price, security_deposit, cleaning_fee, guests_included, extra_people, minimum_nights, maximum_nights, calendar_updated, availability_30, availability_60, availability_90, availability_365, calendar_last_scraped, requires_license, license, instant_bookable, cancellation_policy, require_guest_profile_picture, require_guest_phone_verification, is_business_travel_ready, host_id, host_url, host_name, host_since, host_location, host_about, host_response_time, host_response_rate, host_acceptance_rate, host_is_superhost, host_thumbnail_url, host_picture_url, host_total_listings_count, host_verifications,	host_has_profile_pic, host_identity_verified, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms,	calculated_host_listings_count_shared_rooms, number_of_reviews, number_of_reviews_ltm, reviews_per_month, first_review, last_review, review_scores_rating, review_scores_accuracy,	review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, latitude, longitude, street, is_location_exact, airbnb_region, CT_ID_10, TOWN, COUNTY)
# Correct COUNTY

airbnb$COUNTY <-  ifelse(airbnb$COUNTY == 17, "Middlesex County",
                      ifelse(airbnb$COUNTY == 21, "Norfolk County","Suffolk County"))
############ Save as csv ###########
write.csv(airbnb,"~/Desktop/AIRBNB.Listing.Boston.csv ", row.names = FALSE)
```

